development:
  adapter: mysql2
  encoding: utf8
  database: 
  username: root
  password: 
  host: localhost
  port: 3306  

test:
  adapter: mysql2
  encoding: utf8
  database: 
  username: root
  password: 
  host: localhost
  port: 3306 

production:
  adapter: mysql2
  encoding: utf8
  database: 
  username: root
  password: 
  host: localhost
  port:  
